### ISSUE TITLE
Add more questions

### ISSUE THREAD

**Issue by rahulsain3000** [rahulsain3000/Java_DSA#14]
If you find any java question of any time, add them in `src` folder

All valid PR are accepted with unique question. It can be any thing data structure question or any algorithm or any type of basic question.

Please describe your question and how to approach/solve it in your PR, As it will prepare you to explain your concepts in front of interviewer.
>I am in search of more innovative answer.

**Comment by c99SRS** [comment]
Hi @rahulsain3000 , Can I work on this?

**Comment by rahulsain3000** [comment]
Sure @c99SRS

**Comment by c99SRS** [comment]
@rahulsain3000 , can you please check and merge my change with the Hacktoberfest level?

**Comment by sneha281** [comment]
hey @rahulsain3000 can i work on this this is my very first PR can I?
