### ISSUE TITLE
Implement more code/algorithm for this repo in java language

### ISSUE THREAD

**Issue by rahulsain3000** [rahulsain3000/Java_DSA#24]
Please add your following code in src file with .java extension only.

Accepted any method/algo/code that can fit in this repo

Already exist code will NOT BE ACCEPTED

**Comment by nishantschavan** [comment]
i want to work on it. please assign it to me.

**Comment by oshyam** [comment]
Hi, I would like to contribute.
Thank You.

**Comment by palakdavda22** [comment]
Java being my core language, I have implemented several algorithms in java, please assign me this task.

**Comment by rahulsain3000** [comment]
@palakdavda22 Are you wokring on it?
